# Generated by Django 6.0.3 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type_choices',
            field=models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time'), ('internship', 'internship'), ('contract', 'contract'), ('remote', 'remote')], default='remote', max_length=20),
        ),
    ]
